package kg.geechtech.game.general.players;

public enum SuperAbility {
    HEAL, CRITICAL_DAMAGE, MAGIC_POWER, SAVE_DAMAGE_AND_REVERT, STUN, SELF_DAMAGE, SAVE_LIFE, INVISIBLE, CALL_AN_ASSISTANT,
    STEAL_HEALTH, PRETENDER, POLIMORPH
}
